version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=mysql
      - MYSQL_ROOT_PASSWORD=test
    volumes:
      - 'data:/var/lib/mysql'

volumes:
  data:
